version: '3.8'

services:
  web:
    build:
      context: .
      args:
        - OLD
    command: gunicorn django_site.wsgi:application --bind 0.0.0.0:8000 --timeout 600 --log-level debug
    volumes:
      - static_volume:/webapp/staticfiles
    ports:
      - 8000:8000
    env_file:
      - ./.env
  nginx:
    build: ./nginx
    volumes:
      - static_volume:/webapp/staticfiles
    ports:
      - 80:80
    depends_on:
      - web

volumes:
  static_volume:
